### PR TITLE
Adding aarch64 support

### PR DESCRIPTION
**Pull request by jcapik**

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, we don't support this architecture and don't really plan to at this time. Thanks

**Comment by jcapik** [comment]
> @jcapik @mtwebster we could invert the if statement and test != i386. This would make everyone happy.

Hello :] 
I reworked that a bit in my latest patch. I thought it would be nice to report a bit more than just bit width and therefore it reports "64-bit ARM" now.

[0001-fix-architecture-reporting.txt](https://github.com/user-attachments/files/16400198/0001-fix-architecture-reporting.txt)

I'm not entirely sure where the tool get's the architecture string from, but if it matches the string returned by uname, then there's still a chance someone could get i386, i486, i586 or i686 for the 32-bit architecture depending on the kernel in use and therefore the check for x86_64 makes more sense to me.

**Comment by jcapik** [comment]
This is how it looks ...

Screenshot from 2024-07-27 14-50-26

**Comment by jcapik** [comment]
Just an idea ... If there's no intention to display the architecture, maybe the output of **getconf LONG_BIT** could be used to determine the bit width as it should work on all architectures.

**Comment by jcapik** [comment]
@clefebvre @mtwebster I'm going to create one more pull request that would calculate the bit width from the pointer size, making the whole evaluation architecture independent.

**Comment by jcapik** [comment]
@clefebvre @mtwebster  https://github.com/linuxmint/mintwelcome/pull/66

**Pull request closed without merging**
