### PR TITLE
Use GTK themes instead of hardcoded

### LINKED ISSUE #24: Support for GTK themes
Using Mint-Y-Dark:
image

That theme should be Mint-Y-Dark, so the app should use GTK-theme, not the hardcoded Mint-X theme.

https://github.com/linuxmint/mintwelcome/blob/master/usr/lib/linuxmint/mintwelcome/mintwelcome.py#L187

### PR DESCRIPTION
**Pull request by theel0ja**
Fixes #24

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi,

This is needed to support other themes properly, it doesn't look as nice as it did though when using Mint-X.

Could you detect the GTK theme and keep things as they were when the theme name starts with "Mint-X"?

**Comment by theel0ja** [comment]
Now it looks same as the old using Mint-X (or any color variations of it).

**Comment by theel0ja** [comment]
Whoops, chmodded it `100755 → 100644`...

**Comment by clefebvre** [comment]
thanks :)

**Pull request merged**
